# Generated by Django 3.1.2 on 2020-10-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pollapp", "0003_auto_20201004_1127"),
    ]

    operations = [
        migrations.DeleteModel(name="QuestionAnswerRel",),
    ]
