# Generated by Django 3.1.2 on 2020-10-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollapp", "0005_auto_20201004_1505"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote", name="date", field=models.DateTimeField(auto_now=True),
        ),
    ]
